---
- name: install "{{ item }}"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ack-grep
    - apache2-utils
    - dstat
    - git
    - git-core
    - jq
    - screen
    - sqlite3
    - tmux
    - tree
    - zip
    - zsh
- import_tasks: ctags.yml
- import_tasks: vim.yml
