---
- name: install "{{ item }}"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ack-grep
    - apache2-utils
    - curl
    - fish
    - git
    - git-core
    - htop
    - jq
    - locales
    - sqlite3
    - tree
    - wget
    - whois
    - zip
    - zsh
